# Generated by Django 5.0.4 on 2024-06-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0005_job_created_at_job_status_job_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="first_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="last_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
