# Generated by Django 5.0.4 on 2024-06-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0006_jobapplication_first_name_jobapplication_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
