# Generated by Django 5.0.4 on 2024-06-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0007_jobapplication_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.TextField(null=True),
        ),
    ]
