# Generated by Django 5.0.4 on 2024-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0008_alter_jobapplication_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="question",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="skill",
            field=models.TextField(null=True),
        ),
    ]
