# Generated by Django 5.0.4 on 2024-06-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0009_job_question_job_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job_title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="score",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="transcription",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
