# Generated by Django 5.0.4 on 2024-06-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0010_jobapplication_created_at_jobapplication_job_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="video",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
