# Generated by Django 5.0.4 on 2024-06-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0011_jobapplication_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="analysis",
            field=models.TextField(null=True),
        ),
    ]
